name: Build and Deploy
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Autenticacao no Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        token_format: 'access_token'

    - name: Configurar GCloud SDK
      uses: google-github-actions/setup-gcloud@v1 
      with:
        project_id: ${{ secrets.GCP_PROJECT }}
    
    - name: Autenticar Docker
      shell: pwsh
      run: |
        $env:GCLOUD_KEY=${{ secrets.GCP_SA_KEY }}
        $env:GCLOUD_KEY | Out-File -FilePath "sa-key.json" -Encoding utf8
        gcloud auth activate-service-account --key-file="sa-key.json"
        gcloud auth configure-docker "us-central1-docker.pkg.dev" --quiet
        Remove-Item -Path "sa-key.json"
    
    - name: Build and Push Backend
      working-directory: ./backend
      run: |
        docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/repoextra/backend:latest .
        docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/repoextra/backend:latest
    
    - name: Build and Push Frontend
      working-directory: ./frontend
      run: |
        docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/repoextra/frontend:latest .
        docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/repoextra/frontend:latest
    
    - name: Deploy to GKE
      run: |
        gcloud container clusters get-credentials meu-cluster --zone us-central1-a
        kubectl apply -f mysql-config.yaml
        kubectl apply -f mysql-deployment.yaml
        kubectl apply -f backend-deployment.yaml
        kubectl apply -f backend-service.yaml
        kubectl apply -f frontend-deployment.yaml
        kubectl apply -f frontend-service.yaml